name: Rust

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        run: |
          gh release upload $TAG target/release/pget
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG: ${{ github.ref_name }}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        run: |
          gh release upload $TAG target/release/pget
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG: ${{ github.ref_name }}

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        shell: bash
        run: |
          gh release upload $TAG target/release/pget.exe
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG: ${{ github.ref_name }}
