name: Rust

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        run: |
          tar cfz linux.tar.gz -C target/release pget
          gh release upload $TAG linux.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG: ${{ github.ref_name }}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        run: |
          tar cfz macos_darwin.tar.gz -C target/release pget
          gh release upload $TAG macos_darwin.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG: ${{ github.ref_name }}

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        shell: bash
        run: |
          cd target/release
          7z a windows.zip pget.exe
          gh release upload $TAG windows.zip
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG: ${{ github.ref_name }}
